---
title: "Errata-R"
author: "Martin Frigaard"  
date: "created on `r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Check it out here: https://github.com/mjfrigaard/rrrig

# Repo contents

This is my random collection of R scripts for common tasks. They fall into the general categories below:


```sh
├── README.Rmd
├── README.md
├── functions
│   ├── README.md
│   ├── comcat.R
│   ├── comma.R
│   ├── dataShape.R
│   ├── datevarSum.R
│   ├── fileNamer.R
│   ├── in-not-na-dummies.R
│   ├── mean-sd-mutants.R
│   ├── my-fun.R
│   ├── normVarNames.R
│   ├── numvarSum.R
│   ├── outFile.R
│   ├── pacman-install.R
│   ├── pacman-setup.R
│   ├── sectionLabel.R
│   └── show-missings.R
├── packages
│   └── pacman-install.R
├── rrrig.Rproj
└── templates
    ├── 01.1-project-setup.R
    ├── README.md
    ├── r-script-headers.R
    └── science-journalism-template.Rmd
```

## R functions

These are functions for 

### Functions for wrangling data

* `Data_Wrangling` (otherwise known as data cleaning, munging, etc.)

These are resources, tips, and tools for cleaning/preparing data for visualization and analysis. The scripts are compiled from a variety of resources, but mostly [Modern Data Science in R](https://mdsr-book.github.io/) by Benjamin S. Baumer, Daniel T. Kaplan and Nicholas J. Horton, [Essentials of Data Science](https://essentials.togaware.com/templates/) by Graham J. Williams, and [Data Wrangling with R](https://www.amazon.com/Data-Wrangling-R-Use/dp/3319455982) by Bradley C. Boehmke.


## R templates 

These are file templates (`.R`, `.Rmd`, `.md`, etc.) for working in R. Some have been adapted from other authors, others have been created from scratch. If I used someone else's work and 

## R data
